import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "bootstrap/dist/css/bootstrap.css";
import './custom.scss';
import BootstrapClient from "./Components/BootstrapClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BootstrapClient/>
      </body>
    </html>
  );
}
